
[urgency_low]
    background = "#A3856580"
    foreground = "#FFE6CCE6"
    frame_color = "#C29F7A80"
    icon = "~/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#6B5B3A80"
    foreground = "#FFEECCE6"
    frame_color = "#8F7C5780"
    icon = "~/.config/dunst/icons/hyprdots.svg"
    timeout = 5
